from typing import Protocol
from bussdcc.context import ContextProtocol


class InterfaceProtocol(Protocol):
    name: str

    def attach(self, ctx: ContextProtocol) -> None: ...
    def detach(self) -> None: ...
    def on_start(self, ctx: ContextProtocol) -> None: ...
    def on_stop(self, ctx: ContextProtocol) -> None: ...
