from typing import Protocol

from ..process import ProcessProtocol


class InterfaceManagerProtocol(Protocol):
    def register(self, interface: ProcessProtocol) -> None: ...
    def list(self) -> list[ProcessProtocol]: ...
    def boot(self) -> None: ...
    def shutdown(self) -> None: ...
