from typing import Protocol

from bussdcc.context import ContextProtocol


class DeviceProtocol(Protocol):
    kind: str
    id: str
    ctx: ContextProtocol | None
    online: bool

    def attach(self, ctx: ContextProtocol) -> None: ...
    def detach(self) -> None: ...
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...


class DeviceManagerProtocol(Protocol):
    def attach(self, device: DeviceProtocol, *, booted: bool) -> None: ...
    def detach(self, id: str) -> None: ...
    def list(self, *, kind: str | None = None) -> list[DeviceProtocol]: ...
    def get(self, id: str) -> DeviceProtocol | None: ...
    def boot(self) -> None: ...
    def shutdown(self) -> None: ...
