from datetime import datetime, timezone
from typing import Protocol


class Clock(Protocol):
    def sleep(self, seconds: float) -> None: ...
    def monotonic(self) -> float: ...
    def now_utc(self) -> datetime: ...
